// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpV8687GDb80u3N12CqJ324LoDpeuQNT8',
    appId: '1:903765575810:web:2ba5535d6e8faf0d0fcc9b',
    messagingSenderId: '903765575810',
    projectId: 'salles-176c9',
    authDomain: 'salles-176c9.firebaseapp.com',
    storageBucket: 'salles-176c9.firebasestorage.app',
    measurementId: 'G-7RJXNV0115',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYe0oYHPTk62awkc4PlW2bOScSiRyMwzo',
    appId: '1:903765575810:android:ddfb259f8de501720fcc9b',
    messagingSenderId: '903765575810',
    projectId: 'salles-176c9',
    storageBucket: 'salles-176c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzz7CbjDrlOerpeLHE3jRQys70iEy3ODw',
    appId: '1:903765575810:ios:eaa8bc1f229d738c0fcc9b',
    messagingSenderId: '903765575810',
    projectId: 'salles-176c9',
    storageBucket: 'salles-176c9.firebasestorage.app',
    iosBundleId: 'com.example.vyaparApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzz7CbjDrlOerpeLHE3jRQys70iEy3ODw',
    appId: '1:903765575810:ios:eaa8bc1f229d738c0fcc9b',
    messagingSenderId: '903765575810',
    projectId: 'salles-176c9',
    storageBucket: 'salles-176c9.firebasestorage.app',
    iosBundleId: 'com.example.vyaparApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpV8687GDb80u3N12CqJ324LoDpeuQNT8',
    appId: '1:903765575810:web:f94dbb36272cb3620fcc9b',
    messagingSenderId: '903765575810',
    projectId: 'salles-176c9',
    authDomain: 'salles-176c9.firebaseapp.com',
    storageBucket: 'salles-176c9.firebasestorage.app',
    measurementId: 'G-BZ5YK9JDBY',
  );
}
